#import <Foundation/Foundation.h>
#import "OAIError.h"
#import "OAIPet.h"
#import "OAIApi.h"

/**
* Swagger Petstore
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIPetsApi: NSObject <OAIApi>

extern NSString* kOAIPetsApiErrorDomain;
extern NSInteger kOAIPetsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create a pet
/// 
///
/// 
///  code:201 message:"Null response",
///  code:0 message:"unexpected error"
///
/// @return void
-(NSURLSessionTask*) createPetsWithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// List all pets
/// 
///
/// @param limit How many items to return at one time (max 100) (optional)
/// 
///  code:200 message:"A paged array of pets",
///  code:0 message:"unexpected error"
///
/// @return NSArray<OAIPet>*
-(NSURLSessionTask*) listPetsWithLimit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<OAIPet>* output, NSError* error)) handler;


/// Info for a specific pet
/// 
///
/// @param petId The id of the pet to retrieve
/// @param microchip If the pet has been microchipped (optional) (default to @(NO))
/// 
///  code:200 message:"Expected response to a valid request",
///  code:0 message:"unexpected error"
///
/// @return OAIPet*
-(NSURLSessionTask*) showPetByIdWithPetId: (NSString*) petId
    microchip: (NSNumber*) microchip
    completionHandler: (void (^)(OAIPet* output, NSError* error)) handler;



@end
